version: "3.9"

services:
  api:
    build: .
    container_name: tutoring-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:3000"   # host:container
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./api/public:/usr/src/app/public:ro     # Static SPA files
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    container_name: tutoring-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD","pg_isready","-U","${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  pgdata:
